### PR TITLE
fix(android): add toBack boolean to startCamera

### LINKED ISSUE #49: Camera is always on top on Android after v1.0.3 update
After v1.0.3 update, camera preview shows always on top of any html elements on Android. It seems that the root cause is the deletion of [row 265](https://github.com/capacitor-community/camera-preview/blob/75a7ac471af24e4138e421cf19313d8d98f53dfe/android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java#L265) in `CameraPreview.java`. In fact, adding that line again restores the correct camera preview z-placement on the web view. 

@damngamerz you are the author of the PR where that line has been deleted, can you have a look at this?

### PR DESCRIPTION
**Pull request by damngamerz**
Fixes #49 
I haven't tested this yet. But it should work. (I can only test this tomorrow)

### CODE REVIEW

**Comment by damngamerz** [comment]
@ryaa ^CC

**Comment by sertal70** [comment]
I'll test it today afternoon (Italian time) and give my feedback here.

File: android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java [hunk 1]
```diff
@@ -205,6 +205,7 @@ private void startCamera(final PluginCall call) {
         final Integer width = call.getInt("width", 0);
         final Integer height = call.getInt("height", 0);
         final Integer paddingBottom = call.getInt("paddingBottom", 0);
+        final Boolean toBack = call.getBoolean("toBack", false);
```
Comment (imdadul) [inline android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java:208]: I would name it `placeToFront` and default would be false.
Cause other users of this library already expecting to have this positioned in the back, so it' will be a breaking change for them.

File: android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java [hunk 2]
```diff
@@ -264,7 +265,9 @@ public void run() {
 
                     getBridge().getWebView().setBackgroundColor(Color.TRANSPARENT);
                     ((ViewGroup)getBridge().getWebView().getParent()).addView(containerView);
-
+                    if(toBack == true) {
```
Comment (imdadul) [inline android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java:268]: `if(placeToFront===false)`

**Review by imdadul — CHANGES_REQUESTED** [review]

File: android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java (hunk 1 above)
Comment (damngamerz) [reply android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java:208]: Hmm I agree. But since this project is also similar to `cordova-plugin-camera-preview`. It's interface should also be consistent. https://github.com/capacitor-community/camera-preview/issues/49#issuecomment-684918007

Let's me see what other's think about this. Good point. Thanks for reviewing :+1:

Comment (sertal70) [reply android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java:208]: For what is my understanding, this plugin came to life to offer a replacement for [cordova-plugin-camera-preview](https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview) to anyone migrating from Cordova to Capacitor. Having this in mind, I think that having this plugin behaving like its Cordova counterpart is more important than having a (little) breaking change  My two cents.

**Comment by sertal70** [comment]
@damngamerz I tested the PR and everything is fine with `toBack`. Thank you!

**Comment by damngamerz** [comment]
@ryaa @arielhernandezmusa can we merge and release this?

**Comment by arielhernandezmusa** [comment]
sure
